/**
 * Europe as a pixel grid for the home page journey map (journey-map.js).
 *
 * One character per cell, 176 x 160, Mercator between -12° and 32° longitude and
 * 35° and 61° latitude: "." is sea and "l" is land, and the countries the
 * journey passes through get their own letter so they can be coloured: "i"
 * Italy, "u" the UK, "g" Germany, "e" Spain.
 *
 * Generated once by sampling each cell's centre against the Natural Earth
 * country outlines (world-atlas countries-50m). It's plain data now: to colour
 * another country, change its cells' letter here and give the letter a colour
 * in journey-map.js.
 */

export const BOUNDS = { lon0: -12, lon1: 32, lat0: 35, lat1: 61 };

export const ROWS = [
  "....................................................................lllllllllllllllllllllllllllllllllllllllllllllllll................lllllllllllllllllllllllllllllllllllllllllll",
  "....................................................................lllllllllllllllllllllllllllllllllllllllllllllllll.................llllllllllllllllllllllllllllllllllllllllll",
  "............................................u.......................lllllllllllllllllllllllllllllllllllllllllllllllll.................llllllllllllllllllllllllllllllllllllllllll",
  "..........................................uu..........................llllllllllllllllllllllllllllllllllllllllllllllllll..............lllllllllllllllllllllllllll..lllllllllllll",
  "..........................................u..........................lllll.lllllllllllllllllllllllllllllllllllllllllllll...............llllllllllllllllllll.......llllllllllllll",
  "..........................................uu.........................lllll.lllllllllllllllllllllllllllllllllllllllllllllll.....ll.......llllllllllllllll...........lllllllllllll",
  "..........................................u..........................lllllllllllllllllllllllllllllllllllllllllllllllllllll....lll.........l.lllllllll...............llllllllllll",
  "......................................................................lllllllllllllllllllllllllllllllllllllllllllllllllllll...............l.llllll......................llllllll",
  ".....................................................................l.lllllllllllllllllllllllllllllllllllllllllllllllllllll.................l......................lll..lllllll",
  "....................................................................ll.lllllllllllllllllllllllllllllllllllllllllllllllllllll........................................llllllllllll",
  "....................................................................l..llllllllllllllllllllllllllllllllllllllllllllllllllll.....................................llllllllllllllll",
  ".....................................................................lllllllllllllllllllll.lllllllllllllllllllllllllllllll............................lll.......llllllllllllllll",
  ".....................................................................lll.lllllllllllllllll.llllllllllllllllllllllllllllll........................lllllllllllll..llllllllllllllll",
  ".....................................................................ll.llllllllllllllllll.lllllllllllllllllllllllllllll.l......................llllllllllllllllllllllllllllllll",
  ".....................................................................l..lllllllllllllllll..lllllllllllllllllllllllllllllll....................llllllllllllllllllllllllllllllllll",
  "...................................u....................................lllllllllllllllll.....llllllllllllllllllllllllll.l................l...llllllllllllllllllllllllllllllllll",
  "...................................uu.................................ll.lllllllllllll.......llllllllllllllllllllllllll.................llll..llllllllllllllllllllllllllllllllll",
  "......................................................................llllllllllllllll.......lllllllllllllllllllllllll....................ll..llllllllllllllllllllllllllllllllll",
  "......................................................................lllllllllllllll........lllllllllllllllllllllll..........................llllllllllllllllllllllllllllllllll",
  "............................u..uuuuu...................................lllllllllllll.........llllllllllllllllllllll......................llll.llllllllllllllllllllllllllllllllll",
  "......................u.....uuuuuuuu....................................lllllllllll..........llllllllllllllllllllll.....................llll...lllllllllllllllllllllllllllllllll",
  ".....................uu.....uuuuuuu......................................lllllllll............lllllllllllllllllllll....................llll.....l.llllllllllllllllllllllllllllll",
  "....................uu.....uuuuuuu........................................l.lllll.............lllllllllllllllllllll...............................llllllllllllllllllllllllllllll",
  "....................uu.....uuuuuu.............................................................lllllllllllllllllllll.....................l.........llllllllllllllllllllllllllllll",
  "....................u......uuuuu...............................................................lllllllllllllllllll.........ll....................lllllllllllllllllllllllllllllll",
  ".........................uuuuuuu...............................................................lllllllllllllllllll........ll.....................lllllllllllllllllllllllllllllll",
  "..................uu.....uuuuuuu.uuuuuuuu................................................l......llllllllllllllllll.......ll.............lll......lllllllllllllllllllllllllllllll",
  ".....................uu..uuuuuuuuuuuuuuuu..............................................lll......lllllllllllllllllll......ll............llll.......llllllllllllllllllllllllllllll",
  "..................u...u..uuuuuuuuuuuuuuu...............................................lll......llllllllllllllllll.......ll...........llllll......llllllllllllllllllllllllllllll",
  "..................u....uu.uuuuuuuuuuuuuu..............................................llll.......lllllllllllllllll.......l............lllllll....lllllllllllllllllllllllllllllll",
  "..........................uuuuuuuuuuuuuu..........................................lllllll........lllllllllllllllll.l.....l............lllllll...llllllllllllllllllllllllllllllll",
  ".........................uuuuuuuuuuuuuu...........................................ll.llll.........llllllllllllllll...................lllllllllllllllllllllllllllllllllllllllllll",
  ".........................uuuuuuuuuuuuuu..........................................ll..llll.........lllllllllllllllll.................llllllllllllllllllllllllllllllllllllllllllll",
  "........................uu.uuuuuuuuuuu.............................................llllll..........llllllllllllll.l.................llllllllllllllllllllllllllllllllllllllllllll",
  ".......................uu.uuuuuuuuuuu............................................l.lllllll..........lllllllllllll.l.................llllllllllllllllllllllllllllllllllllllllllll",
  ".......................uu.uuuuuuuuu.u............................................lllllllllll.......lllllllllllll....................llllllllllllllllllllllllllllllllllllllllllll",
  "..........................uuuuuuuuuuu............................................llllllll.l.......llllllllllllll....................llllllllllllllllllllllllllllllllllllllllllll",
  "..........................uuuuuuuuu..............................................llllllll........llllllllll.........................llllllllllllllllllllllllllllllllllllllllllll",
  "........................u..u.uuuuuu.uu...........................................llllllll......lll.lllllll..........................llllllllllllllllllllllllllllllllllllllllllll",
  "......................uu..u.uuuuuuuuuuuu.........................................lllllll..l...l.ll..lllll...........................llllllllllllllllllllllllllllllllllllllllllll",
  ".......................u.u...uuuuuuuuuuuu........................................llllll.....llllll..lllll............................lllllllllllllllllllllllllllllllllllllllllll",
  ".........................u.u.uuuuuuuuuuuu........................................llllll.lll..llll...lllll............................lllllllllllllllllllllllllllllllllllllllllll",
  ".........................u...uuuuuuuuuuuuu........................................lllllllll..llll...lll.l............................lllllllllllllllllllllllllllllllllllllllllll",
  "..................ll.........uuuuuuuuuuuuu.........................................llll.lll..llll..................................l.lllllllllllllllllllllllllllllllllllllllllll",
  "...............llll.uuuu....uuuuuuuuuuuuuu........................................llll...ll....l...........ll........................lllllllllllllllllllllllllllllllllllllllllll",
  "..............lllluuuuuu...uuuuuuuuuuuuuuu.......................................g.lllll.......l.l...................................lllllllllllllllllllllllllllllllllllllllllll",
  "..............lllluuuuuuu...uuuuu.uuuuuuuuu........................................gglg.....llll........................l.......llllllllllllllllllllllllllllllllllllllllllllllll",
  ".............llluuuuuuuu..........uuuuuuuuu........................................ggggg.....ll......g..............llllll......llllllllllllllllllllllllllllllllllllllllllllllll",
  "...............luuuuuuuuuu........uuuuuuuuuuu.......................................gggg.............gg...........llllllll.....lllllllllllllllllllllllllllllllllllllllllllllllll",
  "..............lluuuuuuuuu.........uuuuuuuuuuuu.....................................ggggggg........gg.gg..........llllllllll...llllllllllllllllllllllllllllllllllllllllllllllllll",
  "........lll.l.llluulluuuu....ll....uuuuuuuuuuuu.....................................gggggggg.....ggggg.........lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "........llllllllllllluuu.....l.......uuuuuuuuuuu....................................ggggggg....ggggggggg....llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "........lllllllllllllll.............uuuuuuuuuuu.....................................ggggggggg.ggggggggg.g.llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "..........lllllllllllll.............uuuuuuuuuuuu..................................gggggggggggggggggggggg..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "........lllllllllllllll.............uuuuuuuuuuu..............................ggg..ggggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "........lllllllllllllll.............uuuuuuuuuuuu............................ggggggggggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  ".........llllllllllllll.......u....uuuuuuuuuuuuuu......................lllllggggggggggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "............llllllllllll......uuuuuuuuuuuuuuuuuuu.....................lllllllgggggggggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "...........lllllllllllll.......uuuuuuuuuuuuuuuuuu....................llllllllgggggggggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "..........llllllllllllll......u.uuuuuuuuuuuuuuuu..uuu..............llllllllllgggggggggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "..........lllllllllllll.........uuuuuuuuuuuuuuuuuuuuuuu............lllllllllggggggggggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "...........llllllllllll.........uuuuuuuuuuuuuuuuuuuuuuu...........lllllllllgggggggggggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  ".........llllllllllllll.........uuuuuuuuuuuuuuuuuuuuuuu...........lllllllllgggggggggggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  ".........lllllllllllll.........uuuuuuuuuuuuuuuuuuuuuuuu...........llllllllllggggggggggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "......llllllllllllll..........uuuuuuuuuuuuuuuuuuuuuuuu...........lllllllllllggggggggggggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  ".......llllllllll...........uuuuuuuuuuuuuuuuuuuuuuuuuu..........lllllllllllgggggggggggggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  ".......lllllllll...........uuuuuuuuuuuuuuuuuuuuuuuuuu...........llllllllglggggggggggggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "........llllll..............u..uuuuuuuuuuuuuuuuuuuuu...........lllllllllggggggggggggggggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  ".........lll.....................uuu.uuuuuuuuuuuuuu...........ll.llllllllgggggggggggggggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "....................................uuuuuuuuuuuuuuu..u.......ll..llllllllgggggggggggggggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "................................uu..uuuuuuuuuuuuuuuuuu.....lllllllllllllggggggggggggggggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "...............................uuuuuuuuuuuuuuuuuuuuu......llllllllllllllggggggggggggggggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "..............................uuuuuuuuuuuuuuuuuuuuu....lllllllllllllllllggggggggggggggggggggggggggggggggglglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  ".............................uuuuuuuuuuuuu............llllllllllllllllllggggggggggggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  ".............................uuuuu....................lllllllllllllllllllgggggggggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "............................uuuuuu....................lllllllllllllllllllgggggggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "...........................uu.........................lllllllllllllllllllgggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  ".........................uuu..........................llllllllllllllllllggggggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "....................................................lllllllllllllllllllllgggggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "..................................................llllllllllllllllllllllllggggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  ".........................................ll......lllllllllllllllllllllllllggggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  ".....................................l...ll.......lllllllllllllllllllllllgggggggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  ".........................................lllllllllllllllllllllllllllllllllggggggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "..........................................llllllllllllllllllllllllllllllllllglggggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "..........................................lllllllllllllllllllllllllllllllllllllllgggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "..................................ll......llllllllllllllllllllllllllllllllllllllggggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "..............................lllllll.lll.lllllllllllllllllllllllllllllllllllllgggggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  ".............................llllllllllllllllllllllllllllllllllllllllllllllllllgggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "...............................llllllllllllllllllllllllllllllllllllllllllllllllgggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "...............................lllllllllllllllllllllllllllllllllllllllllllllllggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "..............................llllllllllllllllllllllllllllllllllllllllllllllllggggggggggggggggggggglllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  ".................................lllllllllllllllllllllllllllllllllllllllllllllggggggggggggggggggggggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "....................................llllllllllllllllllllllllllllllllllllllllllgggglllggggggggggggllgllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "......................................llllllllllllllllllllllllllllllllllllllllllllllllllggllggllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "......................................l.llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  ".......................................lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "........................................llllllllllllllllllllllllllllllllllllllllllllllllllllliiiilllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  "........................................lllllllllllllllllllllllllllllllllllllllllllllllllliliiiiilllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
  ".........................................llllllllllllllllllllllllllllllllllllllllllllllllliiiiiiiiiillllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll....",
  "..........................................lllllllllllllllllllllllllllllllllllllllilllilliiiiiiiiiiiiiilllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.....",
  "...........................................llllllllllllllllllllllllllllllllllllliillliiiliiiiiiiiiiiiilllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll...l.",
  "............................................lllllllllllllllllllllllllllllllllllliiiliiiiiiiiiiiiiiiiiillllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll......",
  "............................................llllllllllllllllllllllllllllllllliiiiiiiiiiiiiiiiiiiiiiiiilllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.......",
  "...........................................lllllllllllllllllllllllllllllllliiiiiiiiiiiiiiiiiiiiiiiiiii.llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.........",
  "............................................lllllllllllllllllllllllllllllllliiiiiiiiiiiiiiiiiiiiiii....llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.........",
  "...........................................lllllllllllllllllllllllllllllllllliiiiiiiiiiiiiiiiiiii.....lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.........",
  "...........................................llllllllllllllllllllllllllllllllliiiiiiiiiiiiiiiiiiiii.....lll..llllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.........",
  "...........................................lllllllllllllllllllllllllllllllliiiiiiiiiiiiiiiiiiiiiii.....llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.........",
  "...........................................llllllllllllllllllllllllllllllllliiiiiiiiiiiiiiiiiiiiii.....l.l..llllllllllllllllllllllllllllllllllllllllllllllllllllllllll..........",
  "............................................lllllllllllllllllllllllllllllllliiiiiiiiiiiiiiiiiiiii...........lllllllllllllllllllllllllllllllllllllllllllllllllllllll.............",
  "...........................................lllllllllllllllllllllllllllllllliiiiiiiiiiiiiiiiiiiiii...........lllllllllllllllllllllllllllllllllllllllllllllllllllllll.............",
  "...........................................llllllllllllllllllllllllllllllllliiiiii...iiiiiiiiiiii.............lllllllllllllllllllllllllllllllllllllllllllllllllllll.............",
  "...........................................llllllllllllllllllllllllllllllllllilii......iiiiiiiiiii...........llllllllllllllllllllllllllllllllllllllllllllllllllllll.............",
  "...........................................llllllllllllllllllllllllllllllllllliii........iiiiiiiiii.........l.lllllllllllllllllllllllllllllllllllllllllllllllllllll.............",
  "..........................................lllllllllllllllllllllllllllllllllllli..........iiiiiiiiiiii..........lllllllllllllllllllllllllllllllllllllllllllllllllll..............",
  "...............eeee.....e.................llllllllllllllllllllllllllllllllll.............iiiiiiiiiiiii..........llllllllllllllllllllllllllllllllllllllllllllllllll..............",
  "...............eeeeeeeeeeeeeee.eeee.e....llllllllllllllllllllll...lllllllll...............iiiiiiiiiiiii............lllllllllllllllllllllllllllllllllllllllllllllll..............",
  "............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeelllllllllllllllllll.........lllll...............iiiiiiiiiiiii.............llllllllllllllllllllllllllllllllllllllllllll................",
  "...........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeelllllllllllllllllll.............................iiiiiiiiiiiii...............llllllllllllllllllllllllllllllllllllllllll................",
  "...........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeelllllllllllllll.........................l.....iiiiiiiiiiiii..............llllllllllllllllllllllllllllllllllllllllll................",
  "............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeleelllllll........................ll......iiiiiiiiiiii................lllllllllllllllllllllllllllllllllllllll.................",
  ".............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeelllllll......................lll.......iiiiiiiiiiii................lllllllllllllllllllllllllllllllllllll..................",
  ".............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......................lll........iiiiiiiiiiii.................llllllllllllllllllllllllllllllllllll.................",
  ".............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....................llll.........iiiiiiiiiiii.................llllllllllllllllllllllllllllllllllll................",
  "............elleeeeleeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....................llll..........iiiiiiiiiiii.................lllllllllllllllllllllllllllllllllll................",
  "............lllllllllleeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......................lll...........iiiiiiiiiiiiiiii.............llllllllllllllllllllllllllllllllll................",
  ".............lllllllllleeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.........................ll.............iiiiiiiiiiiiii..............lllllllllllllllllllllllllllllllllll...............",
  ".............llllllllleeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........................................iiiiiiiiiiiii.............llllllllllllllllllllllllllllllllllll.............l",
  ".............lllllllleeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.................................................iiiiiiiiiiii...........llllllllllllllllllllllllllllllllllllll.l........ll",
  ".............llllllleeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee................................ii..................iiiiiiiiiiiii.........llllllllllllllllllllllllllllllllll..llllllllllllll",
  ".............lllllllleeeeeeeeeeeeeeeeeeeeeeeeeeeeee..............................iiiiii.................iiiiiiiiiiiiii........lllllllllllllllllll.......llllll.......lllllllllll",
  ".............lllllllleeeeeeeeeeeeeeeeeeeeeeeeeeeeee..............................iiiiii..................i.iiiiiiiiiiiii.....llllllllllllllllll...l.....lllll.......llllllllllll",
  ".............lllllllleeeeeeeeeeeeeeeeeeeeeeeeeeeee................................iiiii.....................iiiiiiii.iiii.....lllllllllllllllll.......l...l.l..l....llllllllllll",
  ".............llllllleeeeeeeeeeeeeeeeeeeeeeeeeeeee.................................iiiii.....................iiiiiii.....ii....llllllllllll...ll..........lllllllllllllllllllllll",
  ".............llllllleeeeeeeeeeeeeeeeeeeeeeeeeeee...............e..................iiiii......................iiiiii.....ii.....lllllllllll...l.l.........lllllllllllllllllllllll",
  "............lllllllleeeeeeeeeeeeeeeeeeeeeeeeeeee...........ee.....................iiiii........................iii..............lllllllllll.........l....lllllllllllllllllllllll",
  "............lllllleeeeeeeeeeeeeeeeeeeeeeeeeeeee...........eeee....................iiiii........................iii..............llllllllllll.............lllllllllllllllllllllll",
  "...........lllllllleeeeeeeeeeeeeeeeeeeeeeeeeeee............ee.....................iiiii.........................iiii...........l.lllllllllll............l...llllllllllllllllllll",
  "...........lllllllleeeeeeeeeeeeeeeeeeeeeeeeeeee...................................iiii..........................iiii..............lllllllllll...........ll.lllllllllllllllllllll",
  "..........lllllllllleeeeeeeeeeeeeeeeeeeeeeeeeee..................................iii............................iiiii..............lllllllll.............l.lllllllllllllllllllll",
  "..........lllllllllleeeeeeeeeeeeeeeeeeeeeeeeeeee.....e...........................................................ii................llllllll.ll..............llllllllllllllllllll",
  "..........l.llllllleeeeeeeeeeeeeeeeeeeeeeeeeeeeee...............................................................ii................l.llllllll..l............lllllllllllllllllllll",
  "...........lllllllleeeeeeeeeeeeeeeeeeeeeeeeeeee.................................................................ii..................llllllllll.ll......ll...llllllllllllllllllll",
  ".............lllllleeeeeeeeeeeeeeeeeeeeeeeeeee.................................................................iii.....................l...llll.l.......llllllllllllllllllllllll",
  ".............llllllleeeeeeeeeeeeeeeeeeeeeeeee.......................................................ii.....iii.ii.................l..lllll...lll.l.........lllllllllllllllllllll",
  ".............lllllleeeeeeeeeeeeeeeeeeeeeeeeee.....................................................iiiiiiiiiii........................lllllll...l.............lllllllllllllllllll",
  ".............llllleeeeeeeeeeeeeeeeeeeeeeeeeee.....................................................iiiiiiiiiii......................l.llllllll.............ll.lllllllllllllllllll",
  ".............llllleeeeeeeeeeeeeeeeeeeeeeee..........................................................iiiiiiiii.........................lllll.ll...............lllllllllllllllllll",
  ".............llllleeeeeeeeeeeeeeeeeeeeeee.............................................................iiiiiii..........................llll...................llllllllllllllllll",
  "............llllll...eeeeeeeeeeeeeeeeeeee...........................................lllll..............iiiiii.........................llllll..................llllllllllllllllll",
  "......................eeeeeeeeeeeeeeeeee.................................llllll...lllllll..l..............iii..........................l.lll....................llllllllllllllll",
  "......................eeeeeeeee...e........................lllllllll..llllllllllllllllllllll...............i.............................l.l.....l...l........l.l..lllllll....ll",
  ".......................eeeeee........................llllllllllllllllllllllllllllllllllllll.........................................................................llllll......",
  ".......................eeee........................lllllllllllllllllllllllllllllllllllllll......................................................................l....lllll......",
  ".........................e.......................lllllllllllllllllllllllllllllllllllllllll.....................................................................l................",
  "..........................l.....................llllllllllllllllllllllllllllllllllllllllll...............l......................................................................",
  "........................lll..................lllllllllllllllllllllllllllllllllllllllllllllll....................................................................................",
  "........................lll................lllllllllllllllllllllllllllllllllllllllllllllllll..................................................lll...........l...................",
  "........................lllll.............llllllllllllllllllllllllllllllllllllllllllllllllll..................................................lllllllll.........................",
  ".......................llllllllllllllll.llllllllllllllllllllllllllllllllllllllllllllllllllll.......................................................llllll.......................",
];

export const COLS = ROWS[0].length;

const rad = (d) => (d * Math.PI) / 180;
const merc = (lat) => Math.log(Math.tan(Math.PI / 4 + rad(lat) / 2));

/** Projects [lat, lon] to grid cells (fractional), x to the right and y down. */
export function project([lat, lon]) {
  return {
    x: ((lon - BOUNDS.lon0) / (BOUNDS.lon1 - BOUNDS.lon0)) * COLS,
    y: ((merc(BOUNDS.lat1) - merc(lat)) / (merc(BOUNDS.lat1) - merc(BOUNDS.lat0))) * ROWS.length,
  };
}

/** The cell letter at a grid point, or "." off the grid. */
export function cellAt({ x, y }) {
  return ROWS[Math.floor(y)]?.[Math.floor(x)] ?? ".";
}
